package thx.color.palettes;

/**
Colors from [wikipedia](https://en.wikipedia.org/wiki/List_of_colors_(compact)).
**/
class Web {
  public static var aliceblue(default, null) : Rgb;
  public static var antiquewhite(default, null) : Rgb;
  public static var aqua(default, null) : Rgb;
  public static var aquamarine(default, null) : Rgb;
  public static var azure(default, null) : Rgb;
  public static var beige(default, null) : Rgb;
  public static var bisque(default, null) : Rgb;
  public static var black(default, null) : Rgb;
  public static var blanchedalmond(default, null) : Rgb;
  public static var blue(default, null) : Rgb;
  public static var blueviolet(default, null) : Rgb;
  public static var brown(default, null) : Rgb;
  public static var burlywood(default, null) : Rgb;
  public static var cadetblue(default, null) : Rgb;
  public static var chartreuse(default, null) : Rgb;
  public static var chocolate(default, null) : Rgb;
  public static var coral(default, null) : Rgb;
  public static var cornflowerblue(default, null) : Rgb;
  public static var cornsilk(default, null) : Rgb;
  public static var crimson(default, null) : Rgb;
  public static var cyan(default, null) : Rgb;
  public static var darkblue(default, null) : Rgb;
  public static var darkcyan(default, null) : Rgb;
  public static var darkgoldenrod(default, null) : Rgb;
  public static var darkgray(default, null) : Rgb;
  public static var darkgreen(default, null) : Rgb;
  public static var darkgrey(default, null) : Rgb;
  public static var darkkhaki(default, null) : Rgb;
  public static var darkmagenta(default, null) : Rgb;
  public static var darkolivegreen(default, null) : Rgb;
  public static var darkorange(default, null) : Rgb;
  public static var darkorchid(default, null) : Rgb;
  public static var darkred(default, null) : Rgb;
  public static var darksalmon(default, null) : Rgb;
  public static var darkseagreen(default, null) : Rgb;
  public static var darkslateblue(default, null) : Rgb;
  public static var darkslategray(default, null) : Rgb;
  public static var darkslategrey(default, null) : Rgb;
  public static var darkturquoise(default, null) : Rgb;
  public static var darkviolet(default, null) : Rgb;
  public static var deeppink(default, null) : Rgb;
  public static var deepskyblue(default, null) : Rgb;
  public static var dimgray(default, null) : Rgb;
  public static var dimgrey(default, null) : Rgb;
  public static var dodgerblue(default, null) : Rgb;
  public static var firebrick(default, null) : Rgb;
  public static var floralwhite(default, null) : Rgb;
  public static var forestgreen(default, null) : Rgb;
  public static var fuchsia(default, null) : Rgb;
  public static var gainsboro(default, null) : Rgb;
  public static var ghostwhite(default, null) : Rgb;
  public static var gold(default, null) : Rgb;
  public static var goldenrod(default, null) : Rgb;
  public static var gray(default, null) : Rgb;
  public static var green(default, null) : Rgb;
  public static var greenyellow(default, null) : Rgb;
  public static var grey(default, null) : Rgb;
  public static var honeydew(default, null) : Rgb;
  public static var hotpink(default, null) : Rgb;
  public static var indianred(default, null) : Rgb;
  public static var indigo(default, null) : Rgb;
  public static var ivory(default, null) : Rgb;
  public static var khaki(default, null) : Rgb;
  public static var lavender(default, null) : Rgb;
  public static var lavenderblush(default, null) : Rgb;
  public static var lawngreen(default, null) : Rgb;
  public static var lemonchiffon(default, null) : Rgb;
  public static var lightblue(default, null) : Rgb;
  public static var lightcoral(default, null) : Rgb;
  public static var lightcyan(default, null) : Rgb;
  public static var lightgoldenrodyellow(default, null) : Rgb;
  public static var lightgray(default, null) : Rgb;
  public static var lightgreen(default, null) : Rgb;
  public static var lightgrey(default, null) : Rgb;
  public static var lightpink(default, null) : Rgb;
  public static var lightsalmon(default, null) : Rgb;
  public static var lightseagreen(default, null) : Rgb;
  public static var lightskyblue(default, null) : Rgb;
  public static var lightslategray(default, null) : Rgb;
  public static var lightslategrey(default, null) : Rgb;
  public static var lightsteelblue(default, null) : Rgb;
  public static var lightyellow(default, null) : Rgb;
  public static var lime(default, null) : Rgb;
  public static var limegreen(default, null) : Rgb;
  public static var linen(default, null) : Rgb;
  public static var magenta(default, null) : Rgb;
  public static var maroon(default, null) : Rgb;
  public static var mediumaquamarine(default, null) : Rgb;
  public static var mediumblue(default, null) : Rgb;
  public static var mediumorchid(default, null) : Rgb;
  public static var mediumpurple(default, null) : Rgb;
  public static var mediumseagreen(default, null) : Rgb;
  public static var mediumslateblue(default, null) : Rgb;
  public static var mediumspringgreen(default, null) : Rgb;
  public static var mediumturquoise(default, null) : Rgb;
  public static var mediumvioletred(default, null) : Rgb;
  public static var midnightblue(default, null) : Rgb;
  public static var mintcream(default, null) : Rgb;
  public static var mistyrose(default, null) : Rgb;
  public static var moccasin(default, null) : Rgb;
  public static var navajowhite(default, null) : Rgb;
  public static var navy(default, null) : Rgb;
  public static var oldlace(default, null) : Rgb;
  public static var olive(default, null) : Rgb;
  public static var olivedrab(default, null) : Rgb;
  public static var orange(default, null) : Rgb;
  public static var orangered(default, null) : Rgb;
  public static var orchid(default, null) : Rgb;
  public static var palegoldenrod(default, null) : Rgb;
  public static var palegreen(default, null) : Rgb;
  public static var paleturquoise(default, null) : Rgb;
  public static var palevioletred(default, null) : Rgb;
  public static var papayawhip(default, null) : Rgb;
  public static var peachpuff(default, null) : Rgb;
  public static var peru(default, null) : Rgb;
  public static var pink(default, null) : Rgb;
  public static var plum(default, null) : Rgb;
  public static var powderblue(default, null) : Rgb;
  public static var purple(default, null) : Rgb;
  public static var red(default, null) : Rgb;
  public static var rosybrown(default, null) : Rgb;
  public static var royalblue(default, null) : Rgb;
  public static var saddlebrown(default, null) : Rgb;
  public static var salmon(default, null) : Rgb;
  public static var sandybrown(default, null) : Rgb;
  public static var seagreen(default, null) : Rgb;
  public static var seashell(default, null) : Rgb;
  public static var sienna(default, null) : Rgb;
  public static var silver(default, null) : Rgb;
  public static var skyblue(default, null) : Rgb;
  public static var slateblue(default, null) : Rgb;
  public static var slategray(default, null) : Rgb;
  public static var slategrey(default, null) : Rgb;
  public static var snow(default, null) : Rgb;
  public static var springgreen(default, null) : Rgb;
  public static var steelblue(default, null) : Rgb;
  public static var tan(default, null) : Rgb;
  public static var teal(default, null) : Rgb;
  public static var thistle(default, null) : Rgb;
  public static var tomato(default, null) : Rgb;
  public static var turquoise(default, null) : Rgb;
  public static var violet(default, null) : Rgb;
  public static var wheat(default, null) : Rgb;
  public static var white(default, null) : Rgb;
  public static var whitesmoke(default, null) : Rgb;
  public static var yellow(default, null) : Rgb;
  public static var yellowgreen(default, null) : Rgb;

  public static var names(default, null) : Map<String, Rgb>;

  static function __init__() {
    names = new Map();
    names.set("aliceblue", aliceblue = 0xf0f8ff);
    names.set("alice blue", aliceblue);
    names.set("antiquewhite", antiquewhite = 0xfaebd7);
    names.set("antique white", antiquewhite);
    names.set("aqua", aqua = 0x00ffff);
    names.set("aquamarine", aquamarine = 0x7fffd4);
    names.set("azure", azure = 0xf0ffff);
    names.set("beige", beige = 0xf5f5dc);
    names.set("bisque", bisque = 0xffe4c4);
    names.set("black", black = 0x000000);
    names.set("blanchedalmond", blanchedalmond = 0xffebcd);
    names.set("blanched almond", blanchedalmond);
    names.set("blue", blue = 0x0000ff);
    names.set("blueviolet", blueviolet = 0x8a2be2);
    names.set("blue violet", blueviolet);
    names.set("brown", brown = 0xa52a2a);
    names.set("burlywood", burlywood = 0xdeb887);
    names.set("burly wood", burlywood);
    names.set("cadetblue", cadetblue = 0x5f9ea0);
    names.set("cadet blue", cadetblue);
    names.set("chartreuse", chartreuse = 0x7fff00);
    names.set("chart reuse", chartreuse);
    names.set("chocolate", chocolate = 0xd2691e);
    names.set("coral", coral = 0xff7f50);
    names.set("cornflowerblue", cornflowerblue = 0x6495ed);
    names.set("corn flower blue", cornflowerblue);
    names.set("cornsilk", cornsilk = 0xfff8dc);
    names.set("corn silk", cornsilk);
    names.set("crimson", crimson = 0xdc143c);
    names.set("cyan", cyan = 0x00ffff);
    names.set("darkblue", darkblue = 0x00008b);
    names.set("dark blue", darkblue);
    names.set("darkcyan", darkcyan = 0x008b8b);
    names.set("dark cyan", darkcyan);
    names.set("darkgoldenrod", darkgoldenrod = 0xb8860b);
    names.set("dark golden rod", darkgoldenrod);
    names.set("darkgray", darkgray = darkgrey = 0xa9a9a9);
    names.set("dark gray", darkgray);
    names.set("darkgrey", darkgrey);
    names.set("dark grey", darkgrey);
    names.set("darkgreen", darkgreen = 0x006400);
    names.set("dark green", darkgreen);
    names.set("darkkhaki", darkkhaki = 0xbdb76b);
    names.set("dark khaki", darkkhaki);
    names.set("darkmagenta", darkmagenta = 0x8b008b);
    names.set("dark magenta", darkmagenta);
    names.set("darkolivegreen", darkolivegreen = 0x556b2f);
    names.set("dark olive green", darkolivegreen);
    names.set("darkorange", darkorange = 0xff8c00);
    names.set("dark orange", darkorange);
    names.set("darkorchid", darkorchid = 0x9932cc);
    names.set("dark orchid", darkorchid);
    names.set("darkred", darkred = 0x8b0000);
    names.set("dark red", darkred);
    names.set("darksalmon", darksalmon = 0xe9967a);
    names.set("dark salmon", darksalmon);
    names.set("darkseagreen", darkseagreen = 0x8fbc8f);
    names.set("dark sea green", darkseagreen);
    names.set("darkslateblue", darkslateblue = 0x483d8b);
    names.set("dark slate blue", darkslateblue);
    names.set("darkslategray", darkslategray = darkslategrey = 0x2f4f4f);
    names.set("dark slate gray", darkslategray);
    names.set("darkslategrey", darkslategrey);
    names.set("dark slate grey", darkslategrey);
    names.set("darkturquoise", darkturquoise = 0x00ced1);
    names.set("dark turquoise", darkturquoise);
    names.set("darkviolet", darkviolet = 0x9400d3);
    names.set("dark violet", darkviolet);
    names.set("deeppink", deeppink = 0xff1493);
    names.set("deep pink", deeppink);
    names.set("deepskyblue", deepskyblue = 0x00bfff);
    names.set("deep sky blue", deepskyblue);
    names.set("dimgray", dimgray = dimgrey = 0x696969);
    names.set("dim gray", dimgray);
    names.set("dimgrey", dimgrey);
    names.set("dim grey", dimgrey);
    names.set("dodgerblue", dodgerblue = 0x1e90ff);
    names.set("dodger blue", dodgerblue);
    names.set("firebrick", firebrick = 0xb22222);
    names.set("fire brick", firebrick);
    names.set("floralwhite", floralwhite = 0xfffaf0);
    names.set("floral white", floralwhite);
    names.set("forestgreen", forestgreen = 0x228b22);
    names.set("forest green", forestgreen);
    names.set("fuchsia", fuchsia = 0xff00ff);
    names.set("gainsboro", gainsboro = 0xdcdcdc);
    names.set("ghostwhite", ghostwhite = 0xf8f8ff);
    names.set("ghost white", ghostwhite);
    names.set("gold", gold = 0xffd700);
    names.set("goldenrod", goldenrod = 0xdaa520);
    names.set("golden rod", goldenrod);
    names.set("gray", gray = grey = 0x808080);
    names.set("grey", grey);
    names.set("green", green = 0x008000);
    names.set("greenyellow", greenyellow = 0xadff2f);
    names.set("green yellow", greenyellow);
    names.set("honeydew", honeydew = 0xf0fff0);
    names.set("honey dew", honeydew);
    names.set("hotpink", hotpink = 0xff69b4);
    names.set("hot pink", hotpink);
    names.set("indianred", indianred = 0xcd5c5c);
    names.set("indian red", indianred);
    names.set("indigo", indigo = 0x4b0082);
    names.set("ivory", ivory = 0xfffff0);
    names.set("khaki", khaki = 0xf0e68c);
    names.set("lavender", lavender = 0xe6e6fa);
    names.set("lavenderblush", lavenderblush = 0xfff0f5);
    names.set("lavender blush", lavenderblush);
    names.set("lawngreen", lawngreen = 0x7cfc00);
    names.set("lawn green", lawngreen);
    names.set("lemonchiffon", lemonchiffon = 0xfffacd);
    names.set("lemon chiffon", lemonchiffon);
    names.set("lightblue", lightblue = 0xadd8e6);
    names.set("light blue", lightblue);
    names.set("lightcoral", lightcoral = 0xf08080);
    names.set("light coral", lightcoral);
    names.set("lightcyan", lightcyan = 0xe0ffff);
    names.set("light cyan", lightcyan);
    names.set("lightgoldenrodyellow", lightgoldenrodyellow = 0xfafad2);
    names.set("light golden rod yellow", lightgoldenrodyellow);
    names.set("lightgray", lightgray = lightgrey = 0xd3d3d3);
    names.set("light gray", lightgray);
    names.set("lightgrey", lightgrey);
    names.set("light grey", lightgrey);
    names.set("lightgreen", lightgreen = 0x90ee90);
    names.set("light green", lightgreen);
    names.set("lightpink", lightpink = 0xffb6c1);
    names.set("light pink", lightpink);
    names.set("lightsalmon", lightsalmon = 0xffa07a);
    names.set("light salmon", lightsalmon);
    names.set("lightseagreen", lightseagreen = 0x20b2aa);
    names.set("light sea green", lightseagreen);
    names.set("lightskyblue", lightskyblue = 0x87cefa);
    names.set("light sky blue", lightskyblue);
    names.set("lightslategray", lightslategray = lightslategrey = 0x778899);
    names.set("light slate gray", lightslategray);
    names.set("lightslategrey", lightslategrey);
    names.set("light slate grey", lightslategrey);
    names.set("lightsteelblue", lightsteelblue = 0xb0c4de);
    names.set("light steel blue", lightsteelblue);
    names.set("lightyellow", lightyellow = 0xffffe0);
    names.set("light yellow", lightyellow);
    names.set("lime", lime = 0x00ff00);
    names.set("limegreen", limegreen = 0x32cd32);
    names.set("lime green", limegreen);
    names.set("linen", linen = 0xfaf0e6);
    names.set("magenta", magenta = 0xff00ff);
    names.set("maroon", maroon = 0x800000);
    names.set("mediumaquamarine", mediumaquamarine = 0x66cdaa);
    names.set("mediuma quamarine", mediumaquamarine);
    names.set("mediumblue", mediumblue = 0x0000cd);
    names.set("medium blue", mediumblue);
    names.set("mediumorchid", mediumorchid = 0xba55d3);
    names.set("medium orchid", mediumorchid);
    names.set("mediumpurple", mediumpurple = 0x9370db);
    names.set("medium purple", mediumpurple);
    names.set("mediumseagreen", mediumseagreen = 0x3cb371);
    names.set("medium sea green", mediumseagreen);
    names.set("mediumslateblue", mediumslateblue = 0x7b68ee);
    names.set("medium slate blue", mediumslateblue);
    names.set("mediumspringgreen", mediumspringgreen = 0x00fa9a);
    names.set("medium spring green", mediumspringgreen);
    names.set("mediumturquoise", mediumturquoise = 0x48d1cc);
    names.set("medium turquoise", mediumturquoise);
    names.set("mediumvioletred", mediumvioletred = 0xc71585);
    names.set("medium violet red", mediumvioletred);
    names.set("midnightblue", midnightblue = 0x191970);
    names.set("midnight blue", midnightblue);
    names.set("mintcream", mintcream = 0xf5fffa);
    names.set("mint cream", mintcream);
    names.set("mistyrose", mistyrose = 0xffe4e1);
    names.set("misty rose", mistyrose);
    names.set("moccasin", moccasin = 0xffe4b5);
    names.set("navajowhite", navajowhite = 0xffdead);
    names.set("navajo white", navajowhite);
    names.set("navy", navy = 0x000080);
    names.set("oldlace", oldlace = 0xfdf5e6);
    names.set("old lace", oldlace);
    names.set("olive", olive = 0x808000);
    names.set("olivedrab", olivedrab = 0x6b8e23);
    names.set("olive drab", olivedrab);
    names.set("orange", orange = 0xffa500);
    names.set("orangered", orangered = 0xff4500);
    names.set("orange red", orangered);
    names.set("orchid", orchid = 0xda70d6);
    names.set("palegoldenrod", palegoldenrod = 0xeee8aa);
    names.set("pale golden rod", palegoldenrod);
    names.set("palegreen", palegreen = 0x98fb98);
    names.set("pale green", palegreen);
    names.set("paleturquoise", paleturquoise = 0xafeeee);
    names.set("pale turquoise", paleturquoise);
    names.set("palevioletred", palevioletred = 0xdb7093);
    names.set("pale violet red", palevioletred);
    names.set("papayawhip", papayawhip = 0xffefd5);
    names.set("papaya whip", papayawhip);
    names.set("peachpuff", peachpuff = 0xffdab9);
    names.set("peach puff", peachpuff);
    names.set("peru", peru = 0xcd853f);
    names.set("pink", pink = 0xffc0cb);
    names.set("plum", plum = 0xdda0dd);
    names.set("powderblue", powderblue = 0xb0e0e6);
    names.set("powder blue", powderblue);
    names.set("purple", purple = 0x800080);
    names.set("red", red = 0xff0000);
    names.set("rosybrown", rosybrown = 0xbc8f8f);
    names.set("rosy brown", rosybrown);
    names.set("royalblue", royalblue = 0x4169e1);
    names.set("royal blue", royalblue);
    names.set("saddlebrown", saddlebrown = 0x8b4513);
    names.set("saddle brown", saddlebrown);
    names.set("salmon", salmon = 0xfa8072);
    names.set("sandybrown", sandybrown = 0xf4a460);
    names.set("sandy brown", sandybrown);
    names.set("seagreen", seagreen = 0x2e8b57);
    names.set("sea green", seagreen);
    names.set("seashell", seashell = 0xfff5ee);
    names.set("sea shell", seashell);
    names.set("sienna", sienna = 0xa0522d);
    names.set("silver", silver = 0xc0c0c0);
    names.set("skyblue", skyblue = 0x87ceeb);
    names.set("sky blue", skyblue);
    names.set("slateblue", slateblue = 0x6a5acd);
    names.set("slate blue", slateblue);
    names.set("slategray", slategray = slategrey = 0x708090);
    names.set("slate gray", slategray);
    names.set("slategrey", slategrey);
    names.set("slate grey", slategrey);
    names.set("snow", snow = 0xfffafa);
    names.set("springgreen", springgreen = 0x00ff7f);
    names.set("spring green", springgreen);
    names.set("steelblue", steelblue = 0x4682b4);
    names.set("steel blue", steelblue);
    names.set("tan", tan = 0xd2b48c);
    names.set("teal", teal = 0x008080);
    names.set("thistle", thistle = 0xd8bfd8);
    names.set("tomato", tomato = 0xff6347);
    names.set("turquoise", turquoise = 0x40e0d0);
    names.set("violet", violet = 0xee82ee);
    names.set("wheat", wheat = 0xf5deb3);
    names.set("white", white = 0xffffff);
    names.set("whitesmoke", whitesmoke = 0xf5f5f5);
    names.set("white smoke", whitesmoke);
    names.set("yellow", yellow = 0xffff00);
    names.set("yellowgreen", yellowgreen = 0x9acd32);
    names.set("yellow green", yellowgreen);
  }
}
